# This file provides instructions for packaging.

`MooX-late`
	perl_version_from m`MooX::late`;
	version_from      m`MooX::late`;
	readme_from       m`MooX::late`;
	test_requires     p`Test::More 0.61` ;
	.

